version: "3.9"

services:
  LD_connect:
    build:
      context: ./docker/LDCONNECT        
      dockerfile: Dockerfile
    container_name: LDConnect
    environment:
      - EVAL_HOST=ld_eval
      - EVAL_PORT=5001
    env_file:
      - ./docker/LDCONNECT/.env         
    networks:
      - qrapids                 
    depends_on:
      mongodb:                   
        condition: service_started
    ports:
      - "127.0.0.1:5000:5000"    


networks:
  qrapids:
    external: true              
