version: "3.9"

services:
  LD_connect:
    build:
      context: ./LDCONNECT        
      dockerfile: Dockerfile
    container_name: LDConnect
    env_file:
      - ./LDCONNECT/.env         
    networks:
      - qrapids                 
    depends_on:
      mongodb:                   
        condition: service_started
    ports:
      - "127.0.0.1:5000:5000"    

networks:
  qrapids:
    external: true              
