version: "3.9"
services:

  web:
    build: .
    container_name: ld_flask
    # We'll map host port 5000 to container port 5000
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=event_dashboard
    depends_on:
      - mongo

  mongo:
    image: "mongo:6"
    container_name: ld_mongo
    ports:
      - "27017:27017"
